#!/bin/bash

#SBATCH --job-name InterProScan                # Name for your job
#SBATCH --partition=kairos,long                # Partition to submit
#SBATCH --time=96:00:00                        # Total run time limit in HH:MM:SS
#SBATCH --mail-type=end                        # Send email when job ends
#SBATCH --mail-user=eric.torres@alumnos.upm.es # This is the email you wish to be notified at
#SBATCH --mem=15GB                             # Reserve X GB RAM for the job
#SBATCH --cpus-per-task=16                     # Number of cores
#SBATCH --nodes=1                              # Request for cores to be in the same node
#SBATCH --array=0                              # Array range and number of simultanous jobs
#SBATCH --output=ont_%A_%a.out                 # STDERR file
#SBATCH --error=ont_%A_%a.err                  # STDOUT file


##### LOAD YOUR MODULE

module use /beegfs/easybuild/CentOS/7.6.1810/Skylake/modules/all
module use /beegfs/easybuild/common/modules/all

#ml spider singularity
module load singularity/3.2.1

#1. Running InterProScan with Singularity (or Apptainer) on HPC

singularity run --bind /home/sbodi/programs/interproscan/interproscan-5.66-98.0:/opt/interproscan --bind $PWD:/data /home/sbodi/programs/interproscan/interproscan.sif -i /home/erict/my_files_eric/Ct_nuevo/archivos_secuencias/protein.faa -d /data/ -f tsv,gff3 -goterms -cpu 16
