#!/usr/bin/env bash
#SBATCH -c 10
#SBATCH --mem=20GB
#SBATCH -N 1
#SBATCH --job-name namd_protein_1
#SBATCH --output=blat-%a.%A.out # STDOUT file, %j for job id, %N for hostname
#SBATCH --error=blast-%a.%A.err  # STDERR fil
#SBATCH --partition=medium
#SBATCH --time=24:00:00          # total run time limit in HH:MM:SS
#SBATCH --mail-type=end
#SBATCH --mail-user=eric.torres@alumnos.upm.es

### DOWNLOAD PEPTIDASE UNITS AND CREATE BLAST DATABASE
wget https://ftp.ebi.ac.uk/pub/databases/merops/current_release/pepunit.lib

makeblastdb -in pepunit.lib -dbtype prot -out pepunit 

### LOAD YOUR MODULE
module use /beegfs/easybuild/CentOS/7.6.1810/Skylake/modules/all
module use /beegfs/easybuild/common/modules/all

module load BLAST+/2.9.0-gompi-2019a

### RUN YOUR JOB
blastp -query secretome_sequences.fasta -db pepunit -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovs" -out results_merops.txt
